In [1]:
import numpy as np
import pandas as pd
import sklearn

print("Environment Ready")

Environment Ready

In [2]:
df = pd.read_csv("crop_fertilizer.csv")

df.head()

,District_Name,Soil_color,Nitrogen,Phosphorus,Potassium,pH,Rainfall,Temperature,Crop,Fertilizer,Link
0,Kolhapur,Black,75,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
1,Kolhapur,Black,80,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
2,Kolhapur,Black,85,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
3,Kolhapur,Black,90,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
4,Kolhapur,Black,95,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4513 entries, 0 to 4512
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   District_Name  4513 non-null   object
 1   Soil_color     4513 non-null   object
 2   Nitrogen       4513 non-null   int64
 3   Phosphorus     4513 non-null   int64
 4   Potassium      4513 non-null   int64
 5   pH             4513 non-null   float64
 6   Rainfall       4513 non-null   int64
 7   Temperature    4513 non-null   int64
 8   Crop           4513 non-null   object
 9   Fertilizer     4513 non-null   object
 10  Link           4513 non-null   object
dtypes: float64(1), int64(5), object(5)
memory usage: 388.0+ KB

In [4]:
df = df.drop(columns=["Link"])

In [5]:
df.head()

,District_Name,Soil_color,Nitrogen,Phosphorus,Potassium,pH,Rainfall,Temperature,Crop,Fertilizer
0,Kolhapur,Black,75,50,100,6.5,1000,20,Sugarcane,Urea
1,Kolhapur,Black,80,50,100,6.5,1000,20,Sugarcane,Urea
2,Kolhapur,Black,85,50,100,6.5,1000,20,Sugarcane,Urea
3,Kolhapur,Black,90,50,100,6.5,1000,20,Sugarcane,Urea
4,Kolhapur,Black,95,50,100,6.5,1000,20,Sugarcane,Urea

In [6]:
from sklearn.preprocessing import LabelEncoder

le_district = LabelEncoder()
le_soil = LabelEncoder()
le_crop = LabelEncoder()
le_fert = LabelEncoder()

df["District_Name"] = le_district.fit_transform(df["District_Name"])
df["Soil_color"] = le_soil.fit_transform(df["Soil_color"])
df["Crop"] = le_crop.fit_transform(df["Crop"])
df["Fertilizer"] = le_fert.fit_transform(df["Fertilizer"])

# Machine learning models only understand numbers.
# Kolhapur → number
# Black → number
# Sugarcane → number
# Urea → number

In [7]:
df.head()  #yes All is Number

,District_Name,Soil_color,Nitrogen,Phosphorus,Potassium,pH,Rainfall,Temperature,Crop,Fertilizer
0,0,0,75,50,100,6.5,1000,20,11,17
1,0,0,80,50,100,6.5,1000,20,11,17
2,0,0,85,50,100,6.5,1000,20,11,17
3,0,0,90,50,100,6.5,1000,20,11,17
4,0,0,95,50,100,6.5,1000,20,11,17

In [8]:
X = df.drop(["Crop","Fertilizer"], axis=1)

In [9]:
print(X) #Separate Input....

      District_Name  Soil_color  Nitrogen  Phosphorus  Potassium   pH  \
0                 0           0        75          50        100  6.5
1                 0           0        80          50        100  6.5
2                 0           0        85          50        100  6.5
3                 0           0        90          50        100  6.5
4                 0           0        95          50        100  6.5
...             ...         ...       ...         ...        ...  ...
4508              1           0       130          80        150  7.0
4509              1           0       135          80        150  7.0
4510              1           0       140          80        150  7.0
4511              1           0       145          80        150  7.0
4512              1           0       150          80        150  7.0

      Rainfall  Temperature
0         1000           20
1         1000           20
2         1000           20
3         1000           20
4         1000           20
...        ...          ...
4508      1400           30
4509      1400           30
4510      1400           30
4511      1400           30
4512      1400           30

[4513 rows x 8 columns]

In [10]:
y_crop = df["Crop"]
y_fert = df["Fertilizer"]
# Separate Input and Output

In [11]:
print(X.shape)
print(y_crop.shape)
print(y_fert.shape)

(4513, 8)
(4513,)
(4513,)

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_crop_train, y_crop_test = train_test_split(
    X, y_crop, test_size=0.2, random_state=42
)

X_train2, X_test2, y_fert_train, y_fert_test = train_test_split(
    X, y_fert, test_size=0.2, random_state=42
)

#Train-Test Split

In [13]:
# Step-8: Train Model
# Use Random Forest (very good for agriculture datasets).
from sklearn.ensemble import RandomForestClassifier

crop_model = RandomForestClassifier(n_estimators=100)

crop_model.fit(X_train, y_crop_train)

RandomForestClassifier()

In [14]:
fert_model = RandomForestClassifier(n_estimators=100)

fert_model.fit(X_train2, y_fert_train)
#Fertilizer model:

RandomForestClassifier()

In [15]:
#Check Accuracy  - Crop prediction:
from sklearn.metrics import accuracy_score

crop_pred = crop_model.predict(X_test)

print("Crop Accuracy:", accuracy_score(y_crop_test, crop_pred))

Crop Accuracy: 0.9988925802879292

In [16]:
#Fertilizer prediction:
fert_pred = fert_model.predict(X_test2)

print("Fertilizer Accuracy:", accuracy_score(y_fert_test, fert_pred))

Fertilizer Accuracy: 0.9446290143964563

In [17]:
import joblib

joblib.dump(crop_model,"crop_model.pkl")
joblib.dump(fert_model,"fert_model.pkl")

['fert_model.pkl']

In [18]:
sample = [[0, 0, 80, 50, 100, 6.5, 1000, 25]]

prediction = crop_model.predict(sample)

print("Predicted Crop:", prediction)

Predicted Crop: [11]

C:\Users\Swaraj\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [19]:
prediction2 = fert_model.predict(sample)

print("Predicted Fertilizer:", prediction2)

Predicted Fertilizer: [17]

C:\Users\Swaraj\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [20]:
le_crop.inverse_transform(prediction)

array(['Sugarcane'], dtype=object)

In [21]:
le_fert.inverse_transform(prediction2)

array(['Urea'], dtype=object)

In [22]:
crop_name = le_crop.inverse_transform(prediction)[0]

print("Predicted Crop:", crop_name)

Predicted Crop: Sugarcane

In [23]:
crop_name = le_crop.inverse_transform([11])

print("Predicted Crop:", crop_name)

Predicted Crop: ['Sugarcane']

In [36]:
prediction = crop_model.predict(sample)
print(prediction)

[11]

D:\2026\Fertilizer_Recommedation\venv\venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [24]:
le_crop.inverse_transform(prediction)

array(['Sugarcane'], dtype=object)

In [25]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("crop_fertilizer.csv")

le_crop = LabelEncoder()
df["Crop"] = le_crop.fit_transform(df["Crop"])

In [26]:
prediction = crop_model.predict(sample)
print(prediction)

print(le_crop.inverse_transform(prediction))

[11]
['Sugarcane']

C:\Users\Swaraj\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [27]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'crop_fertilizer.csv', 'Crop_Model.ipynb', 'crop_model.pkl', 'fert_model.pkl', 'venv']

In [28]:
import pandas as pd

sample = pd.DataFrame(
    [[0,0,80,50,100,6.5,1000,25]],
    columns=X.columns
)

In [29]:
fert_pred = fert_model.predict(sample)

print(fert_pred)

[17]

In [30]:
sample = pd.DataFrame(
    [[0,0,80,50,100,6.5,1000,25]],
    columns=X.columns
)

fert_pred = fert_model.predict(sample)

fert_name = le_fert.inverse_transform(fert_pred)[0]

print("Predicted Fertilizer:", fert_name)

Predicted Fertilizer: Urea

In [31]:
import pandas as pd

df = pd.read_csv("crop_fertilizer.csv")

In [32]:
from sklearn.preprocessing import LabelEncoder

le_fert = LabelEncoder()

df["Fertilizer_encoded"] = le_fert.fit_transform(df["Fertilizer"])

In [33]:
sample = pd.DataFrame(
    [[0,0,80,50,100,6.5,1000,25]],
    columns=X.columns
)

fert_pred = fert_model.predict(sample)

fert_name = le_fert.inverse_transform(fert_pred)[0]

fert_name = le_fert.inverse_transform(fert_pred)[0]

print("Predicted Fertilizer:", fert_name)

Predicted Fertilizer: Urea

In [34]:
import joblib

joblib.dump(le_fert, "fert_encoder.pkl")

['fert_encoder.pkl']

In [35]:
import joblib

joblib.dump(le_fert, "crop_encoder.pkl")

['crop_encoder.pkl']